// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformDemo;

#nullable disable

namespace PlatformDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230902165741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlatformDemo.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalOrderAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Name = "Customer 1",
                            PhoneNumber = "555-123-01",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 2,
                            Name = "Customer 2",
                            PhoneNumber = "555-123-02",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 3,
                            Name = "Customer 3",
                            PhoneNumber = "555-123-03",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 4,
                            Name = "Customer 4",
                            PhoneNumber = "555-123-04",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 5,
                            Name = "Customer 5",
                            PhoneNumber = "555-123-05",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 6,
                            Name = "Customer 6",
                            PhoneNumber = "555-123-06",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 7,
                            Name = "Customer 7",
                            PhoneNumber = "555-123-07",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 8,
                            Name = "Customer 8",
                            PhoneNumber = "555-123-08",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 9,
                            Name = "Customer 9",
                            PhoneNumber = "555-123-09",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 10,
                            Name = "Customer 10",
                            PhoneNumber = "555-123-10",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 11,
                            Name = "Customer 11",
                            PhoneNumber = "555-123-11",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 12,
                            Name = "Customer 12",
                            PhoneNumber = "555-123-12",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 13,
                            Name = "Customer 13",
                            PhoneNumber = "555-123-13",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 14,
                            Name = "Customer 14",
                            PhoneNumber = "555-123-14",
                            TotalOrderAmount = 0m
                        },
                        new
                        {
                            CustomerId = 15,
                            Name = "Customer 15",
                            PhoneNumber = "555-123-15",
                            TotalOrderAmount = 0m
                        });
                });

            modelBuilder.Entity("PlatformDemo.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Amount = 406m,
                            CustomerId = 1,
                            OrderNumber = "Order-1-1"
                        },
                        new
                        {
                            OrderId = 2,
                            Amount = 97m,
                            CustomerId = 1,
                            OrderNumber = "Order-1-2"
                        },
                        new
                        {
                            OrderId = 3,
                            Amount = 436m,
                            CustomerId = 1,
                            OrderNumber = "Order-1-3"
                        },
                        new
                        {
                            OrderId = 4,
                            Amount = 312m,
                            CustomerId = 1,
                            OrderNumber = "Order-1-4"
                        },
                        new
                        {
                            OrderId = 5,
                            Amount = 160m,
                            CustomerId = 2,
                            OrderNumber = "Order-2-1"
                        },
                        new
                        {
                            OrderId = 6,
                            Amount = 224m,
                            CustomerId = 2,
                            OrderNumber = "Order-2-2"
                        },
                        new
                        {
                            OrderId = 7,
                            Amount = 347m,
                            CustomerId = 2,
                            OrderNumber = "Order-2-3"
                        },
                        new
                        {
                            OrderId = 8,
                            Amount = 419m,
                            CustomerId = 2,
                            OrderNumber = "Order-2-4"
                        },
                        new
                        {
                            OrderId = 9,
                            Amount = 280m,
                            CustomerId = 3,
                            OrderNumber = "Order-3-1"
                        },
                        new
                        {
                            OrderId = 10,
                            Amount = 35m,
                            CustomerId = 3,
                            OrderNumber = "Order-3-2"
                        },
                        new
                        {
                            OrderId = 11,
                            Amount = 146m,
                            CustomerId = 4,
                            OrderNumber = "Order-4-1"
                        },
                        new
                        {
                            OrderId = 12,
                            Amount = 307m,
                            CustomerId = 4,
                            OrderNumber = "Order-4-2"
                        },
                        new
                        {
                            OrderId = 13,
                            Amount = 88m,
                            CustomerId = 4,
                            OrderNumber = "Order-4-3"
                        },
                        new
                        {
                            OrderId = 14,
                            Amount = 462m,
                            CustomerId = 4,
                            OrderNumber = "Order-4-4"
                        },
                        new
                        {
                            OrderId = 15,
                            Amount = 128m,
                            CustomerId = 6,
                            OrderNumber = "Order-6-1"
                        },
                        new
                        {
                            OrderId = 16,
                            Amount = 264m,
                            CustomerId = 7,
                            OrderNumber = "Order-7-1"
                        },
                        new
                        {
                            OrderId = 17,
                            Amount = 145m,
                            CustomerId = 9,
                            OrderNumber = "Order-9-1"
                        },
                        new
                        {
                            OrderId = 18,
                            Amount = 159m,
                            CustomerId = 9,
                            OrderNumber = "Order-9-2"
                        },
                        new
                        {
                            OrderId = 19,
                            Amount = 410m,
                            CustomerId = 9,
                            OrderNumber = "Order-9-3"
                        },
                        new
                        {
                            OrderId = 20,
                            Amount = 489m,
                            CustomerId = 9,
                            OrderNumber = "Order-9-4"
                        },
                        new
                        {
                            OrderId = 21,
                            Amount = 33m,
                            CustomerId = 10,
                            OrderNumber = "Order-10-1"
                        },
                        new
                        {
                            OrderId = 22,
                            Amount = 451m,
                            CustomerId = 10,
                            OrderNumber = "Order-10-2"
                        },
                        new
                        {
                            OrderId = 23,
                            Amount = 290m,
                            CustomerId = 10,
                            OrderNumber = "Order-10-3"
                        },
                        new
                        {
                            OrderId = 24,
                            Amount = 451m,
                            CustomerId = 10,
                            OrderNumber = "Order-10-4"
                        },
                        new
                        {
                            OrderId = 25,
                            Amount = 344m,
                            CustomerId = 11,
                            OrderNumber = "Order-11-1"
                        },
                        new
                        {
                            OrderId = 26,
                            Amount = 50m,
                            CustomerId = 11,
                            OrderNumber = "Order-11-2"
                        },
                        new
                        {
                            OrderId = 27,
                            Amount = 185m,
                            CustomerId = 11,
                            OrderNumber = "Order-11-3"
                        },
                        new
                        {
                            OrderId = 28,
                            Amount = 154m,
                            CustomerId = 12,
                            OrderNumber = "Order-12-1"
                        },
                        new
                        {
                            OrderId = 29,
                            Amount = 481m,
                            CustomerId = 12,
                            OrderNumber = "Order-12-2"
                        },
                        new
                        {
                            OrderId = 30,
                            Amount = 175m,
                            CustomerId = 13,
                            OrderNumber = "Order-13-1"
                        },
                        new
                        {
                            OrderId = 31,
                            Amount = 44m,
                            CustomerId = 13,
                            OrderNumber = "Order-13-2"
                        },
                        new
                        {
                            OrderId = 32,
                            Amount = 116m,
                            CustomerId = 14,
                            OrderNumber = "Order-14-1"
                        });
                });

            modelBuilder.Entity("PlatformDemo.Models.Order", b =>
                {
                    b.HasOne("PlatformDemo.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PlatformDemo.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
